### ISSUE TITLE
参数过多的问题

### ISSUE THREAD

**Issue by flintx** [HaveTwoBrush/cn2an#7]
### 问题描述

在某个程序中引入cn2an库，若运行主程序时包含命令行参数，尤其参数不少于3个的情况下，执行转换必报错。错因：参数过多。

### 个人浅见

cn2an引入了命令行模式，并强制从命令行接收参数。在某程序中调用cn2an方法，即使该程序命令行参数与cn2an无任何关联，例如debug模式、端口号等，cn2an还是会把这些参数视为自身命令行模式的输入，以至于出现参数过多的错误。

可否对考虑命令行模式与程序调用模式进行拆分？

### 相关代码

- [cn2an.py#L40](https://github.com/HaveTwoBrush/cn2an/blob/master/cn2an/cn2an.py#L40)
- [cn2an.py#L53](https://github.com/HaveTwoBrush/cn2an/blob/master/cn2an/cn2an.py#L53)

**Comment by HaveTwoBrush** [comment]
你的理解是正确的，我会在下个版本更新。
