### ISSUE TITLE
较为特殊的要求

### ISSUE THREAD

**Issue by wezhyn** [HaveTwoBrush/cn2an#9]
一二一二 能不能翻译为1212??

**Comment by HaveTwoBrush** [comment]
你所说的这个功能需要和原有的功能共存（使用同一个函数调用）吗？

另外经过你的提醒，我发现现有的功能确实存在一些问题的，比如：

```bash
# bash
cn2an 一二一二
6
```

接下来我可能会考虑进行异常判定，或者将 `一二一二` 转化成 `6`。

**Comment by wezhyn** [comment]
刚刚我写的小项目爬取数据具有有一六二八这种鬼数据..然后cn2an转化为16,我觉得这不太合理,目前通过判断十百千处理这种诡异数据,还是希望出一个附加参数来解决

**Comment by wezhyn** [comment]
> 你所说的这个功能需要和原有的功能共存（使用同一个函数调用）吗？
> 
> 另外经过你的提醒，我发现现有的功能确实存在一些问题的，比如：
> 
> ```shell
> # bash
> cn2an 一二一二
> 6
> ```
> 
> 接下来我可能会考虑进行异常判定，或者将 ` 一二一二 ` 转化成 `1212`。
刚刚我写的小项目爬取数据具有有一六二八这种鬼数据.. 然后 cn2an 转化为 16, 我觉得这不太合理, 目前通过判断十百千处理这种诡异数据, 还是希望出一个附加参数来解决

**Comment by wezhyn** [comment]
> 你所说的这个功能需要和原有的功能共存（使用同一个函数调用）吗？
> 
> 另外经过你的提醒，我发现现有的功能确实存在一些问题的，比如：
> 
> ```shell
> # bash
> cn2an 一二一二
> 6
> ```
> 
> 接下来我可能会考虑进行异常判定，或者将 ` 一二一二 ` 转化成 `1212`。

刚刚我写的小项目爬取数据具有有一六二八这种鬼数据.. 然后 cn2an 转化为 16, 我觉得这不太合理, 目前通过判断十百千处理这种诡异数据, 还是希望出一个附加参数来解决

**Comment by HaveTwoBrush** [comment]
好的，下个小版本我会修复这个问题。

**Comment by wezhyn** [comment]
> 好的，下个小版本我会修复这个问题。

> 

:thumbsup:

**Comment by HaveTwoBrush** [comment]
@wezhyn 更新了一个小版本，但是目前代码还不是特别稳定。你可以使用 `normal` 模式来完成转化，它是一种非严格的转化方式。

下面是一个小例子，详情见 [API](https://github.com/HaveTwoBrush/cn2an/wiki/API)。
```python
# 在 normal 模式下，可以将 一二一二 进行转化
output = cn2an.cn2an("一二一二", "normal")
print(output)
# 1212
```
